### ISSUE TITLE
Converting Half/3-hourly to daily and monthly

### ISSUE THREAD

**Issue by surajitdb** [aazuspan/wxee#27]
Hi, I am wondering if wxee could convert half-hourly / 3-hourly data to daily/ monthly data for the following data sets:
1. ee.ImageCollection("TRMM/3B42") (3-hourly precipitation)
2. ee.ImageCollection("NASA/GPM_L3/IMERG_V06") (half-hourly)

Thanking you.

**Comment by aazuspan** [comment]
Hi @surajitdb, you can use `aggregate_time(frequency="day")` or `aggregate_time(frequency="month")` to do that. 

As long as the frequency of your data is smaller than the frequency you aggregate to, it will work the same. So, for example, using `aggregate_time(frequency="day")` with 12-hour data, 3-hour data, half-hour data, or 5-minute data will always return daily data. The only difference is that 5-minute data would have to aggregate 288 images for every day while 12-hour data would aggregate 2 images per day, so the 5-minute will take longer and use more memory.

**Comment by surajitdb** [comment]
Hi @aazuspan, 
Thank you so much for answering the query promptly. Yes, it did work. I am wondering if there is any way to handle more than 5000 elements at a time in wxee. GEE does not allow the Code Editor to extract more than 5000 elements at a given time. So, for precipitation analysis like ERA5_land, which comes in hourly data wxee could handle elements of 4992 equivalent to 208 days. So, it becomes an issue if we want to handle ERA5_land precipitation for long-term analysis.

**Comment by aazuspan** [comment]
No problem!
