### ISSUE TITLE
How to subset an ImageCollection using a shapefile of an area?

### ISSUE THREAD

**Issue by surajitdb** [aazuspan/wxee#28]
Hi, though wxee serves the purpose of subsetting using a rectangular grid or a country, I am wondering if there is any provision for subsetting using a shapefile of an area like the way we can run on GEE platform using an asset in the form of shapefile file.

Thanking you.

**Comment by aazuspan** [comment]
Yes, that will work. Just load your GEE asset as a `ee.Feature` or `ee.FeatureCollection` and use it like any other geometry.

Something like
```python
# Load an uploaded shapefile asset as a FeatureCollection
my_feature = ee.FeatureCollection("users/aazuspan/fires/mtbs_1984_2018")
# Get the geometry of the first feature
region = my_feature.first().geometry()
```

**Comment by surajitdb** [comment]
Thank you so much @aazuspan for the prompt response to my query. Yes, it worked.
