### ISSUE TITLE
size limit error 

### ISSUE THREAD

**Issue by camile-sothe** [aazuspan/wxee#49]
Hu aazuspan, thank you for providing this package is very helpful!
Im having problems to get images from landsat-8 imageCollection and convert to array due to size limit. I selected only one month period and two bands, but I`m getting an error message unless I set the scale 250m or higher (I wish 30m). Do you know if there is a way to solve this or is a GEE or code restriction this size? Thank you

Error ```"e.ee_exception.EEException: Total request size (238694952 bytes) must be less than or equal to 50331648 bytes."```

My code

```
import ee
import wxee
from geetools import tools

wxee.Initialize()
ee.Initialize()


# Using CONUS C2 ARD tile 2613 tile (assuming there is a better way to import the grid)
aoi = ee.Geometry.Polygon([[[-81.5595250019701439, 32.8743922803664361], [-79.6900076077309478, 32.8743922803664361], [-79.6900076077309478, 34.4158935126628762], [-81.5595250019701439, 34.4158935126628762], [-81.5595250019701439,32.8743922803664361]]])

# Define image collection (here we are using Landsat-8 surface reflectance)
L8= ee.ImageCollection('LANDSAT/LC08/C01/T1_SR')

# Filtering date, study area and selecting bands (in case of not using all of them)
collection = L8.filterDate("2020-07-05", "2020-08-11").filterBounds(aoi).select("B5", "B4")

# The coordinate reference system to use
crs = "EPSG:4326"

# Spatial resolution in CRS units (meters)
## PS: I set 250 otherwise is too big "e.ee_exception.EEException: Total request size (238694952 bytes) must be less than or equal to 50331648 bytes."
scale = 250

arr = collection.wx.to_xarray(scale=scale, crs=crs, region=aoi)

arr

path = "ARD2613_20200705_20200811_B4_B5.nc"

arr = collection.wx.to_xarray(path=path, scale=scale, crs=crs)
```

**Comment by aazuspan** [comment]
Hi @camile-sothe, unfortunately that's a strict size limit from Earth Engine and there's no way around it using `wxee`. The only solutions are to use a larger `scale` (like you've been doing) or use a smaller `region`.
