### ISSUE TITLE
EEException: Date: Parameter 'value' is required.

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [aazuspan/wxee#53]
I was trying to download a median image to xarray and encountered this error below. I understand that we need time series image collections, but wonder if there is a workaround for ee.Image?
Thanks,
Daniel
```
EEException: Date: Parameter 'value' is required.
```

**Comment by aazuspan** [comment]
Currently, `wxee` doesn't support images without time coordinates, but an easy workaround is to set the `system:time_start` property of the image before downloading.

```python
# Set an arbitrary time coordinate
img = img.set("system:time_start", 0)

# Download as usual
img.wx.to_xarray( ... )
```

I can see why it might be convenient to download a single image to xarray without carrying about the time dimension, so I'll think about what it would take to add that option and leave this open for now.
