### ISSUE TITLE
wxee crash in windows WSL linux system

### ISSUE THREAD

**Issue by fanqi203** [aazuspan/wxee#61]
I have a code file to use wxee to convert ee image to xarray array data, and it ran successfully on Windows. 
But when I ran the same piece of code on Windows Subsystem for Linux (WSL) Ubuntu, it crashes. 

Example: 

> import ee
> ee.Initialize()
> import wxee
> wxee.Initialize()
> myregion=ee.Geometry.LineString([[-84, 30], [-70, 45], [-70, 45], [-84, 30]])
> cfsr=[]
> dem=ee.ImageCollection('NOAA/CFSV2/FOR6H').filter(ee.Filter.date('1996-02-14', '1996-02-19')).select(['u component_of_wind_height_above_ground'])
> 
> etc=dem.wx.to_xarray(region=myregion,scale=2000)
> 
> print(etc)

The error was 

> Requesting data:   0%|                                                                                                                            | 0/20 [00:00<?, ?it/s]malloc(): unsorted double linked list corrupted
> Aborted
> 

again, it ran successfully on Windows, but not on WSL.

**Comment by aazuspan** [comment]
I don't have a WSL environment to test with, so I'm not able to reproduce the error. It works on my Ubuntu install.

Based on the error message, it's happening at the C level, which might make it tricky to track down and solve. I found [one mention](https://stackoverflow.com/questions/41753760/python-corrupted-double-linked-list-error) of threading as possible cause for this error in Python.

Can you try re-running with `dem.wx.to_xarray(region=myregion,scale=2000, num_cores=1)`? If communication between threads is the problem, that should solve it by running on a single thread.

**Comment by fanqi203** [comment]
setting num_cores=1 solved the problem. Thank you.

**Comment by aazuspan** [comment]
Glad that worked!
