### ISSUE TITLE
xarray.to_rasterio() 

### ISSUE THREAD

**Issue by benehiebl** [aazuspan/wxee#62]
xr.open_rasterio() doesnt work with the latest xarray package (encountered in wx.to_array(..)).
can be solved easily by adding rioxarray to utils.py (or specify xarray version).

**Comment by aazuspan** [comment]
Thanks for pointing this out @benehiebl! The next release will replace `xarray.open_rasterio` with `rioxarray.open_rasterio`. I'll keep this open until that is released.

**Comment by aazuspan** [comment]
Fix is released in [0.4.0](https://github.com/aazuspan/wxee/releases/tag/v0.4.0)
