### ISSUE TITLE
Missing `plotly.graph_objects` import in `TimeSeries.timeline`

### ISSUE THREAD

**Issue by spgriffin** [aazuspan/wxee#74]
This issue is in the [time_series.ipynb](https://github.com/aazuspan/wxee/blob/254c6508fa0ca0c87c0d384d819da9c7bedd2441/docs/examples/time_series.ipynb) when plotting the time series with call cloudless.timeline().  The call would return, "NameError: name 'go' is not defined."

I was able to correct the issue by adding ```import plotly.graph_objs as go``` to [time_series.py](https://github.com/aazuspan/wxee/blob/254c6508fa0ca0c87c0d384d819da9c7bedd2441/wxee/time_series.py) below ```import plotly.express as px```, line 183

**Comment by aazuspan** [comment]
Great catch, and thanks for tracking down the problem! I'll get that fixed.
